spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: onion
    password: ring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret: 23YBJ4RcuZvXnQ/QBoPoMfHpux5xSHyaY4XsodzYibM=
  expiration: 86400000
